### ISSUE TITLE
Add reference to egghead series?

### ISSUE THREAD

**Issue by kentcdodds** [bahmutov/npm-module-checklist#4]
I think [my egghead.io series](https://egghead.io/series/how-to-write-an-open-source-javascript-library) really helps people get going. Where do you think this fits in?

**Comment by bahmutov** [comment]
I think it is a very useful series and would even add text above the check list

**Comment by kentcdodds** [comment]
Want me to PR it? Or are you adding it as I type this? :smile:

**Comment by bahmutov** [comment]
probably you, I am adding you to the contributors list ;)
